apiVersion: apps/v1
kind: Deployment
metadata:
  name: sock-shop-load-test
  labels:
    name: sock-shop-load-test
  namespace: sock-shop
spec:
  replicas: 3
  selector:
    matchLabels:
      name: sock-shop-load-test
  template:
    metadata:
      labels:
        name: sock-shop-load-test
    spec:
      containers:
      - name: locust
        image: jovalle/locust:v0.1.0
        command: ["/usr/local/bin/runLocust.sh"]
        args: ["-h", "front-end.sock-shop.svc", "-c", "1000"]